export const CREATE_CATEGORY_REQUEST = 'CATEGORY_CREATE_REQUEST';
export const CREATE_CATEGORY_SUCCESS = 'CATEGORY_CREATE_SUCCESS';
export const CREATE_CATEGORY_FAIL = 'CATEGORY_CREATE_FAIL';

export const UPDATE_CATEGORY_REQUEST = 'CATEGORY_UPDATE_REQUEST';
export const UPDATE_CATEGORY_SUCCESS = 'UPDATE_CATEGORY_SUCCESS';
export const UPDATE_CATEGORY_FAIL = 'UPDATE_CATEGORY_FAIL';

export const GET_CATEGORY_LIST_REQUEST = 'GET_CATEGORY_LIST_REQUEST';
export const GET_CATEGORY_LIST_SUCCESS = 'GET_CATEGORY_LIST_SUCCESS';
export const GET_CATEGORY_LIST_FAIL = 'GET_CATEGORY_LIST_FAIL';

export const DELETE_CATEGORY_REQUEST = 'DELETE_CATEGORY_REQUEST';
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';
export const DELETE_CATEGORY_FAIL = 'DELETE_CATEGORY_FAIL';

export const UPDATE_STATUS_CHANGE_REQUEST = 'UPDATE_STATUS_CHANGE_REQUEST';
export const UPDATE_STATUS_CHANGE_SUCCESS = 'UPDATE_STATUS_CHANGE_SUCCESS';
export const UPDATE_STATUS_CHANGE_FAIL = 'UPDATE_STATUS_CHANGE_FAIL';