export const SEND_MESSAGE_REQUEST = 'SEND_MESSAGE_REQUEST';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
export const SEND_MESSAGE_FAIL = 'SEND_MESSAGE_FAIL';

export const GET_MESSAGE_LIST_REQUEST = 'GET_MESSAGE_LIST_REQUEST';
export const GET_MESSAGE_LIST_SUCCESS = 'GET_MESSAGE_LIST_SUCCESS';
export const GET_MESSAGE_LIST_FAIL = 'GET_MESSAGE_LIST_FAIL';

export const DELETE_MESSAGE_REQUEST = 'DELETE_MESSAGE_LIST_REQUEST';
export const DELETE_MESSAGE_SUCCESS = 'DELETE_MESSAGE_LIST_SUCCESS';
export const DELETE_MESSAGE_FAIL = 'DELETE_MESSAGE_LIST_FAIL';