export const GET_USERS_REQUEST = 'GET_USERS_REQUEST';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAIL = 'GET_USERS_FAIL';

export const CREATE_USERS_REQUEST = 'CREATE_USERS_REQUEST';
export const CREATE_USERS_SUCCESS = 'CREATE_USERS_SUCCESS';
export const CREATE_USERS_FAIL = 'CREATE_USERS_FAIL';

export const EDIT_USERS_REQUEST = 'EDIT_USERS_REQUEST';
export const EDIT_USERS_SUCCESS = 'EDIT_USERS_SUCCESS';
export const EDIT_USERS_FAIL = 'EDIT_USERS_FAIL';

export const DELETE_USERS_REQUEST = 'DELETE_USERS_REQUEST';
export const DELETE_USERS_SUCCESS = 'DELETE_USERS_SUCCESS';
export const DELETE_USERS_FAIL = 'DELETE_USERS_FAIL';

export const RESET_PASSWORD_USERS_REQUEST = 'RESET_PASSWORD_USERS_REQUEST';
export const RESET_PASSWORD_USERS_SUCCESS = 'RESET_PASSWORD_USERS_SUCCESS';
export const RESET_PASSWORD_USERS_FAIL = 'RESET_PASSWORD_USERS_FAIL';