export const GET_USER_LIST_REQUEST = 'GET_USER_LIST_REQUEST';
export const GET_USER_LIST_SUCCESS = 'GET_USER_LIST_SUCCESS';
export const GET_USER_LIST_FAIL = 'GET_USER_LIST_FAIL';

export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAIL = 'GET_USER_FAIL';

export const CREATE_USER_REQUEST = 'CREATE_USER_REQUEST';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USERS_FAIL = 'CREATE_USERS_FAIL';

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL';

export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAIL = 'DELETE_USER_FAIL';

export const RESET_PASSWORD_USERS_REQUEST = 'RESET_PASSWORD_USERS_REQUEST';
export const RESET_PASSWORD_USERS_SUCCESS = 'RESET_PASSWORD_USERS_SUCCESS';
export const RESET_PASSWORD_USERS_FAIL = 'RESET_PASSWORD_USERS_FAIL';

export const CHAT_USER_REQUEST = 'CHAT_USER_REQUEST';
export const CHAT_USER_SUCCESS = 'CHAT_USER_SUCCESS';
export const CHAT_USER_FAIL = 'CHAT_USER_FAIL';